-- MySQL Script generated by MySQL Workbench
-- Sat Mar  8 17:42:39 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Colegio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Colegio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Colegio` DEFAULT CHARACTER SET utf8 ;
USE `Colegio` ;

-- -----------------------------------------------------
-- Table `Colegio`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Colegio`.`Aluno` (
  `matricula` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `data_de_nascimento` DATE NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`matricula`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Colegio`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Colegio`.`Professor` (
  `idProfessor` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `especializacao` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  PRIMARY KEY (`idProfessor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Colegio`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Colegio`.`Disciplina` (
  `idDisciplina` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `carga_horaria` INT NOT NULL,
  PRIMARY KEY (`idDisciplina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Colegio`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Colegio`.`Turma` (
  `idTurma` INT NOT NULL,
  `periodo` VARCHAR(45) NOT NULL,
  `id_professor` INT NOT NULL,
  PRIMARY KEY (`idTurma`),
  INDEX `id_professor_idx` (`id_professor` ASC) VISIBLE,
  CONSTRAINT `id_professor`
    FOREIGN KEY (`id_professor`)
    REFERENCES `Colegio`.`Professor` (`idProfessor`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Colegio`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Colegio`.`Matricula` (
  `id_matricula` INT NOT NULL AUTO_INCREMENT,
  `id_aluno` INT NOT NULL,
  `id_turma` INT NOT NULL,
  `data_ingresso` DATE NOT NULL,
  PRIMARY KEY (`id_matricula`),
  INDEX `id_aluno_idx` (`id_aluno` ASC) VISIBLE,
  INDEX `id_turma_idx` (`id_turma` ASC) VISIBLE,
  CONSTRAINT `id_aluno`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `Colegio`.`Aluno` (`matricula`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `id_turma`
    FOREIGN KEY (`id_turma`)
    REFERENCES `Colegio`.`Turma` (`idTurma`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Colegio`.`Notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Colegio`.`Notas` (
  `id_nota` INT NULL AUTO_INCREMENT,
  `id_aluno` INT NOT NULL,
  `id_disciplina` INT NOT NULL,
  `nota` DECIMAL NULL,
  PRIMARY KEY (`id_nota`),
  INDEX `id_aluno_idx` (`id_aluno` ASC) VISIBLE,
  INDEX `id_disciplina_idx` (`id_disciplina` ASC) VISIBLE,
  CONSTRAINT `id_aluno`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `Colegio`.`Aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_disciplina`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `Colegio`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Colegio`.`Frequencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Colegio`.`Frequencia` (
  `id_frequencia` INT NOT NULL AUTO_INCREMENT,
  `id_aluno` INT NOT NULL,
  `id_disciplina` INT NOT NULL,
  `total_presencas` INT NULL,
  PRIMARY KEY (`id_frequencia`),
  INDEX `id_aluno_idx` (`id_aluno` ASC) VISIBLE,
  INDEX `id_disciplina_idx` (`id_disciplina` ASC) VISIBLE,
  CONSTRAINT `id_aluno`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `Colegio`.`Aluno` (`matricula`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `id_disciplina`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `Colegio`.`Disciplina` (`idDisciplina`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Colegio`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Colegio`.`Pagamento` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `id_aluno` INT NOT NULL,
  `data_pagamento` DATE NOT NULL,
  `valor_pago` DECIMAL NOT NULL,
  PRIMARY KEY (`idPagamento`),
  INDEX `id_aluno_idx` (`id_aluno` ASC) VISIBLE,
  CONSTRAINT `id_aluno`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `Colegio`.`Aluno` (`matricula`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
